version: 2.1

executors:
  linux:
    docker:
      - image: circleci/python:3.9.6-buster

jobs:
  Gasi:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: A
          command: |
            ls
            chmod u+x * && ./ec
            


    parallelism: 1
workflows:
  all-Mr:
    jobs:
      - Gasi:
          matrix:
            parameters:
              os: [linux]
              node-version: [8.12.0, 8.13.0]
